name: GitHub Actions Demo
on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: pip install -r src/scraper/requirements.txt
      - run: cd ${{ github.workspace }}/test && ./test.sh
  Package:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: python ${{ github.workspace }}/setup.py build
  Build_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: docker build ${{ github.workspace }} -t ${{ github.sha }}
