name: GitHub Actions Demo
on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: ls ${{ github.workspace }}/test
      #- run: .${{ github.workspace }}/test/test.sh
  Package:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: python ${{ github.workspace }}/setup.sh build
#  Docker:
#    runs-on: ubuntu-latest
#    steps:
#      - run: docker build . -t ${{ github.sha }}
